name: Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Use bash login shell sourcing ~/.bash_profile
        shell: bash -leo pipefail {0}
    steps:

      - name: Context
        run: |
          uname -a
          echo "Number of cores: " `grep -c processor /proc/cpuinfo`
          echo `lscpu | grep "^CPU(s):"`
          echo `lscpu | grep "Thread(s)"`

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build

      - name: Configure
        run: |
          cmake -S . -B .build -G Ninja -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX:PATH=$HOME/usr -DCMAKE_INSTALL_SYSCONFDIR=$HOME/etc

      - name: Make
        run: cd .build; ninja

      - name: Test
        run: |
          cd .build
          ./src/PlatformCompatibilityTests
          ./test/PCTUnittest
          ldd src/PlatformCompatibilityTests
